import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { BatchUpload } from "./BatchUpload";
import { isValidDramaId, makeDramaId, type BatchResponse } from "./batchUploadApi";

function videoFile(name: string): File {
  return new File([new Uint8Array([0, 1, 2])], name, { type: "video/mp4" });
}

function okBatch(): BatchResponse {
  return {
    batch_id: "batch-abc123",
    drama_id: "yunmiao2",
    drama_name: "云渺(新)",
    episodes: [
      {
        episode_id: "ep01",
        name: "第1集",
        duration_seconds: 142.5,
        asr_source: "live",
        proposed_windows: [
          {
            window_id: "w1",
            start_seconds: 41.0,
            end_seconds: 52.0,
            notice_at_seconds: 43.0,
            excerpt: "你到底有没有把我放在眼里",
          },
        ],
      },
    ],
  };
}

/** Drop one or more files into the (hidden) native file input. */
function pickFiles(files: File[]) {
  const input = screen.getByTestId("file-input") as HTMLInputElement;
  fireEvent.change(input, { target: { files } });
}

afterEach(() => {
  vi.unstubAllGlobals();
  vi.restoreAllMocks();
});

describe("BatchUpload", () => {
  it("generates backend-safe internal ids from display names", () => {
    const chinese = makeDramaId("云渺(新)", 12345);
    expect(chinese).toBe("drama_9ix");
    expect(isValidDramaId(chinese)).toBe(true);
    expect(["huangnian", "yunmiao", "lihun"]).not.toContain(chinese);

    const english = makeDramaId("Yun Miao 2", 35);
    expect(english).toBe("yun_miao_2_z");
    expect(isValidDramaId(english)).toBe(true);
  });

  it("disables submit until there is ≥1 file AND a drama name", () => {
    render(<BatchUpload onBatchReady={() => {}} />);
    const submit = screen.getByTestId("submit-batch") as HTMLButtonElement;
    expect(screen.queryByTestId("drama-id")).not.toBeInTheDocument();

    // nothing picked, no name → disabled
    expect(submit).toBeDisabled();

    // a file but still no drama name → disabled
    pickFiles([videoFile("ep1.mp4")]);
    expect(submit).toBeDisabled();

    // a display name is enough; the internal id is generated by the UI.
    fireEvent.change(screen.getByTestId("drama-name"), { target: { value: "云渺(新)" } });
    expect(submit).not.toBeDisabled();
  });

  it("uploads a batch and renders the proposed episodes + windows preview", async () => {
    const fetchMock = vi.fn(async (_url: string, _init?: RequestInit) => ({
      ok: true,
      status: 200,
      json: async () => okBatch(),
    }));
    vi.stubGlobal("fetch", fetchMock as unknown as typeof fetch);

    const onBatchReady = vi.fn();
    render(<BatchUpload onBatchReady={onBatchReady} />);

    pickFiles([videoFile("ep1.mp4")]);
    fireEvent.change(screen.getByTestId("drama-name"), { target: { value: "云渺(新)" } });
    fireEvent.click(screen.getByTestId("submit-batch"));

    // preview renders after the response resolves
    await waitFor(() => expect(screen.getByTestId("proposal-preview")).toBeInTheDocument());
    expect(screen.getByTestId("proposal-episode")).toBeInTheDocument();
    const win = screen.getByTestId("proposal-window");
    expect(win).toHaveTextContent("00:41–00:52");
    expect(win).toHaveTextContent("你到底有没有把我放在眼里");

    // POSTs multipart to /api/studio/batch with the expected fields
    expect(fetchMock).toHaveBeenCalledTimes(1);
    const [url, init] = fetchMock.mock.calls[0];
    expect(url).toBe("/api/studio/batch");
    const reqInit = init as RequestInit;
    expect(reqInit.method).toBe("POST");
    const body = reqInit.body as FormData;
    expect(String(body.get("drama_id"))).toMatch(/^drama_[a-z0-9]+$/);
    expect(body.get("drama_name")).toBe("云渺(新)");
    expect(body.getAll("files")).toHaveLength(1);
    expect(body.getAll("episode_names")).toEqual(["第1集"]);
    // multipart boundary is browser-set, so no explicit Content-Type header
    expect(reqInit.headers).toBeUndefined();

    // "开始制作" hands the full batch up to the parent
    fireEvent.click(screen.getByTestId("start-graph"));
    expect(onBatchReady).toHaveBeenCalledWith(okBatch());
  });

  it("shows a distinct 'backend not ready' state when /api/studio/batch 404s", async () => {
    const fetchMock = vi.fn(async () => ({
      ok: false,
      status: 404,
      json: async () => ({ detail: "Not Found" }),
    }));
    vi.stubGlobal("fetch", fetchMock as unknown as typeof fetch);

    render(<BatchUpload onBatchReady={() => {}} />);
    pickFiles([videoFile("ep1.mp4")]);
    fireEvent.change(screen.getByTestId("drama-name"), { target: { value: "云渺(新)" } });
    fireEvent.click(screen.getByTestId("submit-batch"));

    await waitFor(() => expect(screen.getByTestId("backend-not-ready")).toBeInTheDocument());
    // the generic error panel is NOT shown for a 404 (it's a distinct state)
    expect(screen.queryByTestId("batch-error")).not.toBeInTheDocument();
    // no preview rendered
    expect(screen.queryByTestId("proposal-preview")).not.toBeInTheDocument();
  });

  it("lets the operator name episodes, add more files, and remove a clip", () => {
    render(<BatchUpload onBatchReady={() => {}} />);

    pickFiles([videoFile("a.mp4"), videoFile("b.mp4")]);
    expect(screen.getAllByTestId("clip-row")).toHaveLength(2);

    // defaults are 第1集 / 第2集
    const epInputs = screen.getAllByTestId("episode-name") as HTMLInputElement[];
    expect(epInputs[0].value).toBe("第1集");
    expect(epInputs[1].value).toBe("第2集");

    // rename the first
    fireEvent.change(epInputs[0], { target: { value: "序章" } });
    expect((screen.getAllByTestId("episode-name")[0] as HTMLInputElement).value).toBe("序章");

    // add a third file — appends with default 第3集
    pickFiles([videoFile("c.mp4")]);
    expect(screen.getAllByTestId("clip-row")).toHaveLength(3);
    expect((screen.getAllByTestId("episode-name")[2] as HTMLInputElement).value).toBe("第3集");

    // remove the second
    fireEvent.click(screen.getAllByTestId("remove-clip")[1]);
    expect(screen.getAllByTestId("clip-row")).toHaveLength(2);
  });
});
